name: Validate Blogger XML

on:
  push:
    paths:
      - 'themes/**.xml'
  pull_request:
    paths:
      - 'themes/**.xml'

jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate XML format
        run: |
          xmllint --noout themes/breakup-and-bloom.xml || echo "Fix invalid XML!"
